### PR TITLE
Update PBO Library

### PR DESCRIPTION
**Pull request by FlipperPlz**

### CODE REVIEW

**Comment by FlipperPlz** [comment]
TODO: 
Revert to old LZSS for faster performance.
Debinarize all applicable files (rvmat, config.bin/cpp)

**Comment by FlipperPlz** [comment]
@wrdg The LZSS decompression used in my BiLZSS is the same exact one you have been using, I've only now just realized this. There shouldn't be any performance impact at all since its the same exact code. Everything else has been fixed though. All directories are deleted during cleanup as intended. Any and all binarized rap files will also be debinned.

**Comment by FlipperPlz** [comment]
Ready for merge

**Comment by wrdg** [comment]
lgtm 👍

**Pull request merged**
